'use strict';

// Fixed-width field definitions: [name, start, length]
const FIELDS = [
  ['FEC_MATRICULA',                        0,   8],
  ['COD_CLASE_MAT',                        8,   1],
  ['FEC_TRAMITACION',                      9,   8],
  ['MARCA_ITV',                           17,  30],
  ['MODELO_ITV',                          47,  22],
  ['COD_PROCEDENCIA_ITV',                 69,   1],
  ['BASTIDOR_ITV',                        70,  21],
  ['COD_TIPO',                            91,   2],
  ['COD_PROPULSION_ITV',                  93,   1],
  ['CILINDRADA_ITV',                      94,   5],
  ['POTENCIA_ITV',                        99,   6],
  ['TARA',                               105,   6],
  ['PESO_MAX',                           111,   6],
  ['NUM_PLAZAS',                         117,   3],
  ['IND_PRECINTO',                       120,   2],
  ['IND_EMBARGO',                        122,   2],
  ['NUM_TRANSMISIONES',                  124,   2],
  ['NUM_TITULARES',                      126,   2],
  ['LOCALIDAD_VEHICULO',                 128,  24],
  ['COD_PROVINCIA_VEH',                  152,   2],
  ['COD_PROVINCIA_MAT',                  154,   2],
  ['CLAVE_TRAMITE',                      156,   1],
  ['FEC_TRAMITE',                        157,   8],
  ['CODIGO_POSTAL',                      165,   5],
  ['FEC_PRIM_MATRICULACION',             170,   8],
  ['IND_NUEVO_USADO',                    178,   1],
  ['PERSONA_FISICA_JURIDICA',            179,   1],
  ['CODIGO_ITV',                         180,   9],
  ['SERVICIO',                           189,   3],
  ['COD_MUNICIPIO_INE_VEH',             192,   5],
  ['MUNICIPIO',                          197,  30],
  ['KW_ITV',                            227,   7],
  ['NUM_PLAZAS_MAX',                     234,   3],
  ['CO2_ITV',                           237,   5],
  ['RENTING',                           242,   1],
  ['COD_TUTELA',                         243,   1],
  ['COD_POSESION',                       244,   1],
  ['IND_BAJA_DEF',                       245,   1],
  ['IND_BAJA_TEMP',                      246,   1],
  ['IND_SUSTRACCION',                    247,   1],
  ['BAJA_TELEMATICA',                    248,  11],
  ['TIPO_ITV',                           259,  25],
  ['VARIANTE_ITV',                       284,  25],
  ['VERSION_ITV',                        309,  35],
  ['FABRICANTE_ITV',                     344,  70],
  ['MASA_ORDEN_MARCHA_ITV',              414,   6],
  ['MASA_MAXIMA_TECNICA_ITV',            420,   6],
  ['CATEGORIA_HOMOLOGACION_EUROPEA_ITV', 426,   4],
  ['CARROCERIA',                         430,   4],
  ['PLAZAS_PIE',                         434,   3],
  ['NIVEL_EMISIONES_EURO_ITV',           437,   8],
  ['CONSUMO_WH_KM_ITV',                  445,   4],
  ['CLASIFICACION_REGLAMENTO_VEHICULOS_ITV', 449, 4],
  ['CATEGORIA_VEHICULO_ELECTRICO',       453,   4],
  ['AUTONOMIA_VEHICULO_ELECTRICO',       457,   6],
  ['MARCA_VEHICULO_BASE',                463,  30],
  ['FABRICANTE_VEHICULO_BASE',           493,  50],
  ['TIPO_VEHICULO_BASE',                 543,  35],
  ['VARIANTE_VEHICULO_BASE',             578,  25],
  ['VERSION_VEHICULO_BASE',              603,  35],
  ['DISTANCIA_EJES_12_ITV',             638,   4],
  ['VIA_ANTERIOR_ITV',                   642,   4],
  ['VIA_POSTERIOR_ITV',                  646,   4],
  ['TIPO_ALIMENTACION_ITV',              650,   1],
  ['CONTRASENA_HOMOLOGACION_ITV',        651,  25],
  ['ECO_INNOVACION_ITV',                 676,   1],
  ['REDUCCION_ECO_ITV',                  677,   4],
  ['CODIGO_ECO_ITV',                     681,  25],
  ['FEC_PROCESO',                        706,   8],
];

const FIELD_MAP = Object.fromEntries(FIELDS.map(([name, start, len]) => [name, { start, len }]));

function getField(line, name) {
  const { start, len } = FIELD_MAP[name];
  return line.substring(start, start + len).trim();
}

module.exports = { FIELDS, FIELD_MAP, getField };
