'use strict';

// INE Comunidades Autónomas (2-digit codes) — official INE codification.
const COMUNIDADES_AUTONOMAS = [
  ['01', 'Andalucía'],
  ['02', 'Aragón'],
  ['03', 'Asturias, Principado de'],
  ['04', 'Balears, Illes'],
  ['05', 'Canarias'],
  ['06', 'Cantabria'],
  ['07', 'Castilla y León'],
  ['08', 'Castilla-La Mancha'],
  ['09', 'Cataluña'],
  ['10', 'Comunitat Valenciana'],
  ['11', 'Extremadura'],
  ['12', 'Galicia'],
  ['13', 'Madrid, Comunidad de'],
  ['14', 'Murcia, Región de'],
  ['15', 'Navarra, Comunidad Foral de'],
  ['16', 'País Vasco'],
  ['17', 'Rioja, La'],
  ['18', 'Ceuta'],
  ['19', 'Melilla'],
];

// INE provincias (2-digit codes, matching the first 2 digits of the 5-digit
// municipio code) mapped to name and their comunidad autónoma code.
const PROVINCIAS = [
  ['01', 'Araba/Álava', '16'],
  ['02', 'Albacete', '08'],
  ['03', 'Alicante/Alacant', '10'],
  ['04', 'Almería', '01'],
  ['05', 'Ávila', '07'],
  ['06', 'Badajoz', '11'],
  ['07', 'Balears, Illes', '04'],
  ['08', 'Barcelona', '09'],
  ['09', 'Burgos', '07'],
  ['10', 'Cáceres', '11'],
  ['11', 'Cádiz', '01'],
  ['12', 'Castellón/Castelló', '10'],
  ['13', 'Ciudad Real', '08'],
  ['14', 'Córdoba', '01'],
  ['15', 'Coruña, A', '12'],
  ['16', 'Cuenca', '08'],
  ['17', 'Girona', '09'],
  ['18', 'Granada', '01'],
  ['19', 'Guadalajara', '08'],
  ['20', 'Gipuzkoa', '16'],
  ['21', 'Huelva', '01'],
  ['22', 'Huesca', '02'],
  ['23', 'Jaén', '01'],
  ['24', 'León', '07'],
  ['25', 'Lleida', '09'],
  ['26', 'Rioja, La', '17'],
  ['27', 'Lugo', '12'],
  ['28', 'Madrid', '13'],
  ['29', 'Málaga', '01'],
  ['30', 'Murcia', '14'],
  ['31', 'Navarra', '15'],
  ['32', 'Ourense', '12'],
  ['33', 'Asturias', '03'],
  ['34', 'Palencia', '07'],
  ['35', 'Palmas, Las', '05'],
  ['36', 'Pontevedra', '12'],
  ['37', 'Salamanca', '07'],
  ['38', 'Santa Cruz de Tenerife', '05'],
  ['39', 'Cantabria', '06'],
  ['40', 'Segovia', '07'],
  ['41', 'Sevilla', '01'],
  ['42', 'Soria', '07'],
  ['43', 'Tarragona', '09'],
  ['44', 'Teruel', '02'],
  ['45', 'Toledo', '08'],
  ['46', 'Valencia/València', '10'],
  ['47', 'Valladolid', '07'],
  ['48', 'Bizkaia', '16'],
  ['49', 'Zamora', '07'],
  ['50', 'Zaragoza', '02'],
  ['51', 'Ceuta', '18'],
  ['52', 'Melilla', '19'],
];

// Maps each provincia id to the "región" name used in AEMET's clima/*.csv
// files (db/clima/*_1991_2020_Provincias.csv), which use different
// capitalization/accents/word order than the INE names above.
const PROVINCIA_CLIMA_REGION = {
  '01': 'ARABA/ALAVA',
  '02': 'ALBACETE',
  '03': 'ALICANTE/ALACANT',
  '04': 'ALMERIA',
  '05': 'AVILA',
  '06': 'BADAJOZ',
  '07': 'ILLES BALEARS',
  '08': 'BARCELONA',
  '09': 'BURGOS',
  '10': 'CACERES',
  '11': 'CADIZ',
  '12': 'CASTELLON/CASTELLÓ',
  '13': 'CIUDAD REAL',
  '14': 'CORDOBA',
  '15': 'A CORUÑA',
  '16': 'CUENCA',
  '17': 'GIRONA',
  '18': 'GRANADA',
  '19': 'GUADALAJARA',
  '20': 'GIPUZKOA',
  '21': 'HUELVA',
  '22': 'HUESCA',
  '23': 'JAEN',
  '24': 'LEON',
  '25': 'LLEIDA',
  '26': 'LA RIOJA',
  '27': 'LUGO',
  '28': 'MADRID',
  '29': 'MALAGA',
  '30': 'MURCIA',
  '31': 'NAVARRA',
  '32': 'OURENSE',
  '33': 'ASTURIAS',
  '34': 'PALENCIA',
  '35': 'LAS PALMAS',
  '36': 'PONTEVEDRA',
  '37': 'SALAMANCA',
  '38': 'SANTA CRUZ DE TENERIFE',
  '39': 'CANTABRIA',
  '40': 'SEGOVIA',
  '41': 'SEVILLA',
  '42': 'SORIA',
  '43': 'TARRAGONA',
  '44': 'TERUEL',
  '45': 'TOLEDO',
  '46': 'VALENCIA/VALÈNCIA',
  '47': 'VALLADOLID',
  '48': 'BIZKAIA',
  '49': 'ZAMORA',
  '50': 'ZARAGOZA',
  '51': 'CEUTA',
  '52': 'MELILLA',
};

module.exports = { COMUNIDADES_AUTONOMAS, PROVINCIAS, PROVINCIA_CLIMA_REGION };
