'use strict';

/**
 * Curación manual (investigación web, agosto 2026) de precio base (PVP
 * oficial España, versión más básica cuando hay varias) y etiquetas para los
 * vehiculos más matriculados (top 200 por matriculaciones).
 *
 * `id` corresponde a vehiculos.id en el momento de la investigación — estable
 * entre ejecuciones de build-vehiculos.js gracias al upsert por clave natural
 * (MARCA_ITV_NORMALIZADO, MODELO_ITV_NORMALIZADO, POTENCIA_ITV). `marca` y
 * `modelo` se verifican antes de escribir para detectar si esa estabilidad
 * se rompiera alguna vez.
 *
 * Para volver a aplicar (p. ej. tras recrear vehiculos desde cero con
 * build-vehiculos.js): node curate-vehiculos.js
 *
 * Vehiculos omitidos por tener modelo no identificable en la DGT ("N.A.",
 * "N/A", "NOT APPLICABLE"): ids 19 (SHERCO), 59 (RIEJU), 62 (RIEJU), 63
 * (BETA), 247 (RIEJU). También el id 40 (LETBE HJ125T-5B): código interno
 * sin correspondencia comercial identificable con confianza.
 */

const CURATED = [
  // --- Top 1-30 ---
  { id: 17, marca: 'YAMAHA', modelo: 'NMAX 125', precio: 3599, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Scooter Urban'] },
  { id: 26, marca: 'HONDA', modelo: 'PCX 125', precio: 3499, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Scooter Urban'] },
  { id: 30, marca: 'ZONTES', modelo: '368G', precio: 4888, tags: ['Scooter', 'Crossover', 'Adventure', 'Media (300-400cc)', 'Carné A2', 'Mixta', 'Scooter Adventure'] },
  { id: 18, marca: 'ZONTES', modelo: '125X', precio: 2688, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 16, marca: 'SYM', modelo: 'SYMPHONY 125', precio: 2399, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 3, marca: 'VOGE', modelo: 'DS800X RALLY', precio: 7888, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', 'Carné A', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 21, marca: 'HONDA', modelo: 'SH125i', precio: 4190, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Premium', 'Scooter Urban'] },
  { id: 115, marca: 'HONDA', modelo: 'FORZA125', precio: 5550, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'City/Commuting', 'Carretera', '125cc', 'Carné A1', 'Premium', 'Scooter Sport'] },
  { id: 8, marca: 'KYMCO', modelo: 'AGILITY S', precio: 2450, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 28, marca: 'HONDA', modelo: 'ADV 350', precio: 6740, tags: ['Scooter', 'Crossover', 'Adventure', 'Media (300-400cc)', 'Carné A2', 'Mixta', 'Scooter Adventure'] },
  { id: 51, marca: 'YAMAHA', modelo: 'XMAX 125', precio: 5499, tags: ['Scooter', 'Deportivo', 'City/Commuting', 'Carretera', '125cc', 'Carné A1', 'Premium', 'Scooter Sport'] },
  { id: 23, marca: 'VOGE', modelo: 'DS900X', precio: 9192, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', 'Carné A2', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 10, marca: 'SYM', modelo: 'JET 14', precio: 2599, tags: ['Scooter', 'Urbana', 'Compacto', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 55, marca: 'YAMAHA', modelo: 'RayZR 125', precio: 2399, tags: ['Scooter', 'Urbana', 'Bajo consumo', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 64, marca: 'HONDA', modelo: 'VISION 110', precio: 2599, tags: ['Scooter', 'Urbana', 'Bajo consumo', 'City/Commuting', 'Ligera (110-124cc)', 'Carné A1', 'Económica', 'Compacto', 'Scooter Urban'] },
  { id: 35, marca: 'RIEJU', modelo: 'RALLY 307', precio: 4499, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Media (300-400cc)', 'Carné A2', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 78, marca: 'VOGE', modelo: '625DSX', precio: 6592, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', 'Carné A2', 'Off-road/Aventura', 'Mixta', 'Trail Turismo'] },
  { id: 7, marca: 'PIAGGIO', modelo: 'LIBERTY 125 ABS', precio: 2999, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 110, marca: 'YAMAHA', modelo: 'XMAX 300', precio: 6499, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'Carretera', 'Turismo', 'Media (300-400cc)', 'Carné A2', 'Premium', 'Scooter Sport'] },
  { id: 9, marca: 'HONDA', modelo: 'ADV 750', precio: 13500, tags: ['Scooter', 'Crossover', 'Adventure', 'Grande (600cc+)', 'Carné A2', 'Off-road/Aventura', 'Premium', 'Mixta', 'Scooter Adventure'] },
  { id: 159, marca: 'YAMAHA', modelo: 'MT-07', precio: 7799, tags: ['Moto Naked', 'Deportivo', 'Grande (600cc+)', 'Carné A2', 'Carretera'] },
  { id: 6, marca: 'ZONTES', modelo: '125C', precio: 3087, tags: ['Moto Custom', 'Clásico', '125cc', 'Carné A1', 'Económica', 'Urbana', 'Carretera'] },
  { id: 70, marca: 'YAMAHA', modelo: 'XTZ 700 Tenere', precio: 11199, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', 'Carné A', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 4, marca: 'KAWASAKI', modelo: 'Z900', precio: 10235, tags: ['Moto Naked', 'Deportivo', 'Grande (600cc+)', 'Carné A', 'Carretera'] },
  { id: 91, marca: 'HONDA', modelo: 'XL750 Transalp', precio: 9990, tags: ['Trail', 'Moto Adventure', 'Moto Touring', 'Adventure', 'Grande (600cc+)', 'Carné A', 'Off-road/Aventura', 'Mixta', 'Trail Turismo'] },
  { id: 76, marca: 'KYMCO', modelo: 'SKYTOWN 125', precio: 2750, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 93, marca: 'APRILIA', modelo: 'SR GT 125', precio: 3350, tags: ['Scooter', 'Deportivo', 'City/Commuting', 'Carretera', '125cc', 'Carné A1', 'Premium', 'Scooter Sport'] },
  { id: 69, marca: 'BMW', modelo: 'R 1300 GS', precio: 22230, tags: ['Trail', 'Moto Adventure', 'Moto Touring', 'Grand Turismo', 'Adventure', 'Grande (600cc+)', '700cc+', 'Carné A', 'Off-road/Aventura', 'Mixta', 'Premium', 'Trail Turismo'] },
  { id: 34, marca: 'KYMCO', modelo: 'DTX', precio: 3690, tags: ['Scooter', 'Crossover', 'Adventure', '125cc', 'Carné A1', 'Económica', 'Mixta', 'Scooter Adventure'] },

  // --- 31-100 ---
  { id: 12, marca: 'HONDA', modelo: 'SH Mode 125', precio: 3050, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 149, marca: 'YAMAHA', modelo: 'TMAX 560', precio: 14299, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'Turismo', 'Carné A2', 'Premium', 'Scooter Sport'] },
  { id: 37, marca: 'CFMOTO', modelo: '450MT', precio: 5995, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Carné A2', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 199, marca: 'VOGE', modelo: 'R125', precio: 3087, tags: ['Moto Naked', '125cc', 'Carné A1', 'Económica', 'Urbana', 'Carretera'] },
  { id: 25, marca: 'ZONTES', modelo: '125E', precio: 3887, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Scooter Urban'] },
  { id: 61, marca: 'ZONTES', modelo: '703RR', precio: 7688, tags: ['Moto Sport', 'Deportivo', 'Grande (600cc+)', '700cc+', 'Carné A2', 'Carretera'] },
  { id: 200, marca: 'HONDA', modelo: 'FORZA 350', precio: 6500, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'Media (300-400cc)', 'Carné A2', 'Premium', 'Scooter Sport'] },
  { id: 111, marca: 'VOGE', modelo: 'SR1ADV', precio: 2992, tags: ['Scooter', 'Crossover', 'Adventure', '125cc', 'Carné A1', 'Económica', 'Scooter Adventure'] },
  { id: 140, marca: 'VOGE', modelo: 'DS525X', precio: 5392, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Carné A2', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 81, marca: 'HONDA', modelo: 'FORZA 750', precio: 12390, tags: ['Scooter', 'Crossover', 'Adventure', 'Grande (600cc+)', 'Carné A2', 'Premium', 'Mixta', 'Scooter Adventure'] },
  { id: 193, marca: 'PIAGGIO', modelo: 'VESPA PRIMAVERA 125', precio: 4499, tags: ['Scooter', 'Clásico', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Premium', 'Scooter Urban'] },
  { id: 43, marca: 'YAMAHA', modelo: 'MT-125', precio: 5499, tags: ['Moto Naked', 'Deportivo', '125cc', 'Carné A1', 'Urbana', 'Carretera'] },
  { id: 197, marca: 'SILENCE', modelo: 'S01', precio: 3600, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Bajo consumo', 'Carné A1', 'Premium', 'Scooter Urban'] },
  { id: 166, marca: 'YAMAHA', modelo: 'MT-09', precio: 11299, tags: ['Moto Naked', 'Deportivo', 'Grande (600cc+)', 'Carné A2', 'Carretera'] },
  { id: 5, marca: 'KYMCO', modelo: 'SUPER DINK GT 125 E5+', precio: 4250, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'City/Commuting', '125cc', 'Carné A1', 'Premium', 'Scooter Sport'] },
  { id: 147, marca: 'ZONTES', modelo: '703F', precio: 7288, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', '700cc+', 'Carné A', 'Off-road/Aventura', 'Trail Turismo'] },
  { id: 119, marca: 'HONDA', modelo: 'NX500', precio: 6450, tags: ['Trail', 'Moto Adventure', 'Crossover', 'Adventure', 'Carné A2', 'Off-road/Aventura', 'Mixta', 'Trail Deportiva'] },
  { id: 122, marca: 'QJMOTOR', modelo: 'ATR 125 E5+', precio: 3199, tags: ['Scooter', 'Crossover', 'Adventure', '125cc', 'Carné A1', 'Económica', 'Scooter Adventure'] },
  { id: 44, marca: 'KYMCO', modelo: 'AGILITY 16+50', precio: 2296, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Económica', 'Compacto', 'Scooter Urban'] },
  { id: 144, marca: 'BMW', modelo: 'R 1300 GS ADVENTURE', precio: 24940, tags: ['Trail', 'Moto Adventure', 'Moto Touring', 'Grand Turismo', 'Adventure', 'Grande (600cc+)', '700cc+', 'Carné A', 'Off-road/Aventura', 'Mixta', 'Premium', 'Trail Turismo'] },
  { id: 99, marca: 'PEUGEOT', modelo: 'KISBEE M', precio: 1199, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Económica', 'Compacto', 'Scooter Urban'] },
  { id: 38, marca: 'HONDA', modelo: 'SH350i', precio: 6400, tags: ['Scooter', 'Urbana', 'Premium', 'Media (300-400cc)', 'Carné A2', 'City/Commuting', 'Scooter Urban'] },
  { id: 151, marca: 'PIAGGIO', modelo: 'MEDLEY 125', precio: 3500, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Scooter Urban'] },
  { id: 203, marca: 'SYM', modelo: 'JET X', precio: 3399, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 67, marca: 'VOGE', modelo: 'R125S', precio: 3999, tags: ['Moto Naked', 'Deportivo', '125cc', 'Carné A1', 'Carretera'] },
  { id: 176, marca: 'ZONTES', modelo: '368E', precio: 4592, tags: ['Scooter', 'Crossover', 'Adventure', 'Media (300-400cc)', 'Carné A2', 'Mixta', 'Scooter Adventure'] },
  { id: 47, marca: 'QJMOTOR', modelo: 'MTX 125 E5+', precio: 2999, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 227, marca: 'HONDA', modelo: 'NC 750 X', precio: 9090, tags: ['Trail', 'Moto Adventure', 'Moto Touring', 'Adventure', 'Grande (600cc+)', '700cc+', 'Carné A2', 'Off-road/Aventura', 'Mixta', 'Trail Turismo'] },
  { id: 114, marca: 'KYMCO', modelo: 'DTX', precio: 4650, tags: ['Scooter', 'Crossover', 'Adventure', 'Media (300-400cc)', 'Carné A2', 'Mixta', 'Scooter Adventure'] },
  { id: 157, marca: 'HONDA', modelo: 'CB650RA', precio: 9100, tags: ['Moto Naked', 'Deportivo', 'Grande (600cc+)', 'Carné A2', 'Carretera'] },
  { id: 88, marca: 'YAMAHA', modelo: 'TRACER 700', precio: 9999, tags: ['Moto Touring', 'Trail', 'Adventure', 'Grande (600cc+)', 'Carné A2', 'Carretera', 'Turismo', 'Trail Turismo'] },
  { id: 223, marca: 'BMW', modelo: 'F 800 GS', precio: 11180, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', 'Carné A2', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 74, marca: 'HONDA', modelo: 'CB750 Hornet', precio: 8350, tags: ['Moto Naked', 'Deportivo', 'Grande (600cc+)', '700cc+', 'Carné A2', 'Carretera'] },
  { id: 101, marca: 'VOGE', modelo: 'SR1', precio: 2792, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'City/Commuting', '125cc', 'Carné A1', 'Scooter Sport'] },
  { id: 304, marca: 'HONDA', modelo: 'CBR 650 R', precio: 11000, tags: ['Moto Sport', 'Deportivo', 'Grande (600cc+)', 'Carné A2', 'Carretera'] },
  { id: 206, marca: 'BMW', modelo: 'C 400 GT', precio: 10340, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'Media (300-400cc)', 'Carné A2', 'Premium', 'Scooter Sport'] },
  { id: 103, marca: 'YAMAHA', modelo: 'Tracer 9 GT', precio: 16390, tags: ['Moto Touring', 'Grand Turismo', 'Grande (600cc+)', '700cc+', 'Carné A', 'Carretera', 'Turismo', 'Premium'] },
  { id: 291, marca: 'ZONTES', modelo: 'ZT125-G1', precio: 3287, tags: ['Moto Naked', '125cc', 'Carné A1', 'Urbana', 'Carretera', 'Económica'] },
  { id: 214, marca: 'HONDA', modelo: 'CRF1100L Africa Twin', precio: 15975, tags: ['Trail', 'Moto Adventure', 'Moto Touring', 'Adventure', 'Grande (600cc+)', '700cc+', 'Carné A', 'Off-road/Aventura', 'Mixta', 'Premium', 'Trail Turismo'] },
  { id: 342, marca: 'MACBOR', modelo: 'MONTANA XR1 125 EVO', precio: 3499, tags: ['Trail', 'Moto Adventure', 'Adventure', '125cc', 'Carné A1', 'Off-road/Aventura', 'Económica', 'Trail Deportiva'] },
  { id: 123, marca: 'RIEJU', modelo: 'NKD 125', precio: 3149, tags: ['Moto Naked', 'Deportivo', '125cc', 'Carné A1', 'Urbana', 'Carretera', 'Económica'] },
  { id: 210, marca: 'QJMOTOR', modelo: 'FORT 125 N E5+', precio: 3999, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'City/Commuting', '125cc', 'Carné A1', 'Scooter Sport'] },
  { id: 136, marca: 'VOGE', modelo: 'SR16', precio: 2688, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 216, marca: 'YAMAHA', modelo: 'WR125', precio: 4699, tags: ['Trail', 'Moto Adventure', 'Adventure', '125cc', 'Carné A1', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 150, marca: 'SYM', modelo: 'JET 14', precio: 2299, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Económica', 'Compacto', 'Scooter Urban'] },
  { id: 238, marca: 'BMW', modelo: 'R 1300 RT', precio: 25060, tags: ['Moto Touring', 'Grand Turismo', 'Grande (600cc+)', '700cc+', 'Carné A', 'Carretera', 'Turismo', 'Premium'] },
  { id: 619, marca: 'SUZUKI', modelo: 'ADDRESS 125', precio: 2599, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Bajo consumo', 'Compacto', 'Scooter Urban'] },
  { id: 355, marca: 'ZONTES', modelo: '125D', precio: 3487, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Scooter Urban'] },
  { id: 268, marca: 'ZONTES', modelo: 'ZT125-Z2', precio: 3287, tags: ['Moto Naked', '125cc', 'Carné A1', 'Urbana', 'Carretera', 'Económica'] },
  { id: 14, marca: 'ZONTES', modelo: '368K', precio: 4592, tags: ['Scooter', 'Crossover', 'Adventure', 'Media (300-400cc)', 'Carné A2', 'Mixta', 'Scooter Adventure'] },
  { id: 145, marca: 'KYMCO', modelo: 'SUPER DINK GT', precio: 4299, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'Turismo', 'Media (300-400cc)', 'Carné A2', 'Scooter Sport'] },
  { id: 285, marca: 'BMW', modelo: 'F 900 R', precio: 9960, tags: ['Moto Naked', 'Deportivo', 'Grande (600cc+)', '700cc+', 'Carné A2', 'Carretera'] },
  { id: 269, marca: 'HONDA', modelo: 'GB350S', precio: 4590, tags: ['Moto Custom', 'Clásico', 'Media (300-400cc)', 'Carné A2', 'Urbana', 'Carretera'] },
  { id: 48, marca: 'HONDA', modelo: 'Rebel 500', precio: 6450, tags: ['Moto Custom', 'Clásico', 'Carné A2', 'Urbana', 'Carretera'] },
  { id: 75, marca: 'YAMAHA', modelo: 'R125', precio: 5799, tags: ['Moto Sport', 'Deportivo', '125cc', 'Carné A1', 'Carretera', 'Premium'] },
  { id: 42, marca: 'KYMCO', modelo: 'PEOPLE S 125 E5+', precio: 2950, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Scooter Urban'] },
  { id: 153, marca: 'KAWASAKI', modelo: 'Z650', precio: 7750, tags: ['Moto Naked', 'Deportivo', 'Grande (600cc+)', 'Carné A2', 'Carretera'] },
  { id: 102, marca: 'BMW', modelo: 'F 900 GS', precio: 14210, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', 'Carné A2', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 60, marca: 'SUZUKI', modelo: 'GSX-8S', precio: 6499, tags: ['Moto Naked', 'Deportivo', 'Grande (600cc+)', '700cc+', 'Carné A2', 'Carretera'] },
  { id: 128, marca: 'VOGE', modelo: '300RALLY', precio: 3792, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Media (300-400cc)', 'Carné A2', 'Off-road/Aventura', 'Económica', 'Trail Deportiva'] },
  { id: 56, marca: 'HONDA', modelo: 'CBF 125', precio: 2999, tags: ['Moto Naked', 'Urbana', '125cc', 'Carné A1', 'Económica', 'Carretera'] },
  { id: 49, marca: 'SUZUKI', modelo: 'V-Strom 800', precio: 8999, tags: ['Trail', 'Moto Adventure', 'Moto Touring', 'Adventure', 'Grande (600cc+)', '700cc+', 'Carné A2', 'Off-road/Aventura', 'Mixta', 'Trail Turismo'] },
  { id: 126, marca: 'KTM', modelo: 'KTM 390 ADVENTURE R', precio: 7499, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Media (300-400cc)', 'Carné A2', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 127, marca: 'KEEWAY', modelo: 'XDV 125 EVO PRO', precio: 3190, tags: ['Scooter', 'Crossover', 'Adventure', '125cc', 'Carné A1', 'Económica', 'Scooter Adventure'] },
  { id: 45, marca: 'PEUGEOT', modelo: 'KISBEE S', precio: 2099, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Económica', 'Compacto', 'Scooter Urban'] },
  { id: 279, marca: 'SYM', modelo: 'ADX 300 TCS', precio: 4599, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'Media (300-400cc)', 'Carné A2', 'Scooter Sport'] },
  { id: 29, marca: 'MH MOTORCYCLES', modelo: 'TRAY', precio: 3495, tags: ['Trail', 'Moto Adventure', 'Adventure', '125cc', 'Carné A1', 'Off-road/Aventura', 'Económica', 'Trail Deportiva'] },
  { id: 292, marca: 'KAWASAKI', modelo: 'NINJA ZX-6R', precio: 13395, tags: ['Moto Sport', 'Deportivo', 'Grande (600cc+)', 'Carné A', 'Carretera', 'Premium'] },
  { id: 294, marca: 'KAWASAKI', modelo: 'KLE500', precio: 6500, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Media (300-400cc)', 'Carné A2', 'Off-road/Aventura', 'Trail Deportiva'] },

  // --- 101-200 ---
  { id: 161, marca: 'KOVE', modelo: 'KOVE 800 X GT', precio: 7999, tags: ['Trail', 'Moto Adventure', 'Moto Touring', 'Adventure', 'Grande (600cc+)', 'Carné A2', 'Off-road/Aventura', 'Mixta', 'Trail Turismo'] },
  { id: 316, marca: 'HONDA', modelo: 'CB 125 F', precio: 2999, tags: ['Moto Naked', 'Urbana', '125cc', 'Carné A1', 'Económica', 'Carretera'] },
  { id: 171, marca: 'KOVE', modelo: 'KOVE 800 X PRO 2026', precio: 7999, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', 'Carné A2', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 135, marca: 'ROYAL ENFIELD', modelo: 'HIMALAYAN 452', precio: 5400, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Carné A2', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 92, marca: 'BMW', modelo: 'F 900 XR', precio: 12950, tags: ['Moto Touring', 'Grand Turismo', 'Grande (600cc+)', 'Carné A2', 'Carretera', 'Turismo', 'Premium'] },
  { id: 53, marca: 'CFMOTO', modelo: '1000MT-X', precio: 9990, tags: ['Trail', 'Moto Adventure', 'Moto Touring', 'Adventure', 'Grande (600cc+)', '700cc+', 'Carné A', 'Off-road/Aventura', 'Mixta', 'Trail Turismo'] },
  { id: 80, marca: 'SYM', modelo: 'SYMPHONY 50', precio: 2299, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Económica', 'Compacto', 'Scooter Urban'] },
  { id: 400, marca: 'CFMOTO', modelo: '675SR-R', precio: 7995, tags: ['Moto Sport', 'Deportivo', 'Grande (600cc+)', '700cc+', 'Carné A2', 'Carretera'] },
  { id: 124, marca: 'QJMOTOR', modelo: 'SRK 125 S E5+', precio: 3299, tags: ['Moto Naked', 'Deportivo', '125cc', 'Carné A1', 'Carretera'] },
  { id: 52, marca: 'CYCLONE', modelo: 'RX2', precio: 3999, tags: ['Trail', 'Moto Adventure', 'Adventure', '125cc', 'Carné A1', 'Off-road/Aventura', 'Económica', 'Trail Deportiva'] },
  { id: 95, marca: 'PIAGGIO', modelo: 'VESPA GTS 125', precio: 6250, tags: ['Scooter', 'Clásico', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Premium', 'Scooter Urban'] },
  { id: 370, marca: 'VOGE', modelo: 'SR3', precio: 3992, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'Carné A2', 'Scooter Sport'] },
  { id: 573, marca: 'BMW', modelo: 'C 400 X', precio: 7960, tags: ['Scooter', 'Crossover', 'Adventure', 'Media (300-400cc)', 'Carné A2', 'Premium', 'Mixta', 'Scooter Adventure'] },
  { id: 39, marca: 'PEUGEOT', modelo: 'PULSION EVO', precio: 3399, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'City/Commuting', '125cc', 'Carné A1', 'Scooter Sport'] },
  { id: 133, marca: 'KTM', modelo: 'KTM 125 DUKE', precio: 5299, tags: ['Moto Naked', 'Deportivo', '125cc', 'Carné A1', 'Carretera', 'Premium'] },
  { id: 362, marca: 'HONDA', modelo: 'NT1100', precio: 15600, tags: ['Moto Touring', 'Grand Turismo', 'Grande (600cc+)', '700cc+', 'Carné A', 'Carretera', 'Turismo', 'Premium'] },
  { id: 523, marca: 'KTM', modelo: 'KTM 300 EXC', precio: 11195, tags: ['Trail', 'Off-road/Aventura', 'Carné A', 'Premium'] },
  { id: 278, marca: 'ZONTES', modelo: 'ZT125-U', precio: 3287, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Scooter Urban'] },
  { id: 156, marca: 'QJMOTOR', modelo: 'SQ 16 E5+', precio: 2899, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 361, marca: 'APRILIA', modelo: 'SXR 50', precio: 2270, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Deportivo', 'Económica', 'Compacto', 'Scooter Urban'] },
  { id: 50, marca: 'BAJAJ', modelo: 'PULSAR NS 125', precio: 2699, tags: ['Moto Naked', 'Deportivo', '125cc', 'Carné A1', 'Carretera', 'Económica'] },
  { id: 120, marca: 'ZONTES', modelo: '368D', precio: 4192, tags: ['Scooter', 'Deportivo', 'Urbana', 'Media (300-400cc)', 'Carné A2', 'Scooter Sport'] },
  { id: 98, marca: 'YAMAHA', modelo: 'YZF-R9', precio: 16000, tags: ['Moto Sport', 'Deportivo', 'Grande (600cc+)', '700cc+', 'Carné A', 'Carretera', 'Premium'] },
  { id: 87, marca: 'KEEWAY', modelo: 'VIESTE 125', precio: 2190, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 172, marca: 'BENDA', modelo: 'NAPOLEON 125', precio: 4790, tags: ['Moto Custom', 'Clásico', '125cc', 'Carné A1', 'Urbana', 'Carretera', 'Premium'] },
  { id: 1, marca: 'CFMOTO', modelo: '800MT-X', precio: 7995, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', 'Carné A', 'Off-road/Aventura', 'Mixta', 'Trail Deportiva'] },
  { id: 237, marca: 'HONDA', modelo: 'CRF 300 L', precio: 6050, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Carné A2', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 395, marca: 'BMW', modelo: 'F 450 GS', precio: 7390, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Carné A2', 'Off-road/Aventura', 'Premium', 'Trail Deportiva'] },
  { id: 134, marca: 'SYM', modelo: 'CRUISYM 125 TCS E5+', precio: 4499, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'City/Commuting', '125cc', 'Carné A1', 'Scooter Sport'] },
  { id: 83, marca: 'YAMAHA', modelo: 'XSR-125', precio: 4999, tags: ['Moto Naked', 'Clásico', '125cc', 'Carné A1', 'Urbana', 'Carretera', 'Premium'] },
  { id: 284, marca: 'MH MOTORCYCLES', modelo: 'VR10', precio: 3195, tags: ['Scooter', 'Crossover', 'Adventure', '125cc', 'Carné A1', 'Económica', 'Mixta', 'Scooter Adventure'] },
  { id: 100, marca: 'VOGE', modelo: '625R', precio: 5184, tags: ['Moto Naked', 'Deportivo', 'Grande (600cc+)', 'Carné A2', 'Carretera'] },
  { id: 22, marca: 'ZONTES', modelo: 'ZT125-U1', precio: 3387, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Scooter Urban'] },
  { id: 314, marca: 'DUCATI', modelo: 'MULTISTRADA V2', precio: 15290, tags: ['Trail', 'Moto Adventure', 'Moto Touring', 'Adventure', 'Grande (600cc+)', 'Carné A2', 'Off-road/Aventura', 'Mixta', 'Premium', 'Trail Turismo'] },
  { id: 340, marca: 'SUZUKI', modelo: 'GSX-S 1000', precio: 12499, tags: ['Moto Naked', 'Deportivo', 'Grande (600cc+)', '700cc+', 'Carné A', 'Carretera', 'Premium'] },
  { id: 72, marca: 'SILENCE', modelo: 'S02', precio: 3490, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Bajo consumo', 'Compacto', 'Económica', 'Scooter Urban'] },
  { id: 148, marca: 'SUZUKI', modelo: 'AVENIS 125', precio: 2959, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Scooter Urban'] },
  { id: 211, marca: 'SYM', modelo: 'ADX 125 LC TCS E5+', precio: 3999, tags: ['Scooter', 'Crossover', 'Adventure', 'City/Commuting', '125cc', 'Carné A1', 'Mixta', 'Scooter Adventure'] },
  { id: 233, marca: 'KYMCO', modelo: 'SKYTOWN 125', precio: 2750, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 485, marca: 'KAWASAKI', modelo: 'NINJA 650', precio: 8585, tags: ['Moto Sport', 'Deportivo', 'Grande (600cc+)', 'Carné A2', 'Carretera'] },
  { id: 1059, marca: 'KOVE', modelo: 'KOVE 800 X PRO', precio: 7999, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', 'Carné A2', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 77, marca: 'KAWASAKI', modelo: 'NINJA ZX-4R', precio: 9450, tags: ['Moto Sport', 'Deportivo', 'Media (300-400cc)', 'Carné A2', 'Carretera', 'Premium'] },
  { id: 79, marca: 'STARK', modelo: 'VARG', precio: 12490, tags: ['Off-road/Aventura', 'Premium'] },
  { id: 146, marca: 'HERO MOTOCORP', modelo: 'X PULSE 200 4V', precio: 2592, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Carné A2', 'Off-road/Aventura', 'Económica', 'Trail Deportiva'] },
  { id: 118, marca: 'QJMOTOR', modelo: 'SRV 125 E5+', precio: 3299, tags: ['Moto Custom', 'Clásico', '125cc', 'Carné A1', 'Urbana', 'Carretera', 'Económica'] },
  { id: 265, marca: 'QJMOTOR', modelo: 'SRT 900 S', precio: 8699, tags: ['Trail', 'Moto Adventure', 'Moto Touring', 'Adventure', 'Grande (600cc+)', '700cc+', 'Carné A', 'Off-road/Aventura', 'Mixta', 'Trail Turismo'] },
  { id: 320, marca: 'KEEWAY', modelo: 'RKS 125', precio: 1990, tags: ['Moto Naked', 'Urbana', '125cc', 'Carné A1', 'Económica', 'Carretera'] },
  { id: 566, marca: 'BMW', modelo: 'S 1000 XR', precio: 18800, tags: ['Moto Touring', 'Grand Turismo', 'Grande (600cc+)', '700cc+', 'Carné A', 'Carretera', 'Turismo', 'Premium'] },
  { id: 390, marca: 'KAWASAKI', modelo: 'VERSYS 650', precio: 9050, tags: ['Trail', 'Moto Adventure', 'Moto Touring', 'Adventure', 'Grande (600cc+)', 'Carné A2', 'Off-road/Aventura', 'Mixta', 'Trail Turismo'] },
  { id: 254, marca: 'BMW', modelo: 'R 1300 RS', precio: 18330, tags: ['Moto Sport', 'Deportivo', 'Grande (600cc+)', '700cc+', 'Carné A', 'Carretera', 'Premium'] },
  { id: 84, marca: 'KTM', modelo: 'KTM 1390 SUPER ADVENTU', precio: 22299, tags: ['Trail', 'Moto Adventure', 'Moto Touring', 'Adventure', 'Grande (600cc+)', '700cc+', 'Carné A', 'Off-road/Aventura', 'Mixta', 'Premium', 'Trail Turismo'] },
  { id: 141, marca: 'DUCATI', modelo: 'MULTISTRADA V4', precio: 22790, tags: ['Trail', 'Moto Adventure', 'Moto Touring', 'Adventure', 'Grande (600cc+)', '700cc+', 'Carné A', 'Off-road/Aventura', 'Mixta', 'Premium', 'Trail Turismo'] },
  { id: 94, marca: 'ZONTES', modelo: '368M', precio: 4192, tags: ['Scooter', 'Deportivo', 'Urbana', 'Media (300-400cc)', 'Carné A2', 'Scooter Sport'] },
  { id: 240, marca: 'PEUGEOT', modelo: 'TWEET FL 125 CC', precio: 2695, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 300, marca: 'PIAGGIO', modelo: 'VESPA GTS', precio: 5999, tags: ['Scooter', 'Clásico', 'Urbana', 'Media (300-400cc)', 'Carné A2', 'Premium', 'Scooter Urban'] },
  { id: 163, marca: 'MOTO MORINI', modelo: 'X-CAPE 1200', precio: 11990, tags: ['Trail', 'Moto Adventure', 'Moto Touring', 'Adventure', 'Grande (600cc+)', '700cc+', 'Carné A', 'Off-road/Aventura', 'Mixta', 'Trail Turismo'] },
  { id: 68, marca: 'MH MOTORCYCLES', modelo: 'VRT', precio: 2795, tags: ['Scooter', 'Clásico', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 349, marca: 'HONDA', modelo: 'CBR500', precio: 7250, tags: ['Moto Sport', 'Deportivo', 'Carné A2', 'Carretera'] },
  { id: 65, marca: 'YAMAHA', modelo: 'R7', precio: 10499, tags: ['Moto Sport', 'Deportivo', 'Grande (600cc+)', 'Carné A2', 'Carretera', 'Premium'] },
  { id: 217, marca: 'BMW', modelo: 'F 900 GS ADVENTURE', precio: 15400, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', 'Carné A2', 'Off-road/Aventura', 'Mixta', 'Premium', 'Trail Deportiva'] },
  { id: 27, marca: 'QJMOTOR', modelo: 'SRT 900 SX', precio: 8999, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', '700cc+', 'Carné A', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 165, marca: 'KAWASAKI', modelo: 'Z1100', precio: 12450, tags: ['Moto Naked', 'Deportivo', 'Grande (600cc+)', '700cc+', 'Carné A', 'Carretera', 'Premium'] },
  { id: 33, marca: 'KOVE', modelo: 'KOVE 800 X RALLY', precio: 10699, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', 'Carné A2', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 121, marca: 'QJMOTOR', modelo: 'SRT 600 SX E5+', precio: 5999, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Carné A2', 'Off-road/Aventura', 'Económica', 'Trail Deportiva'] },
  { id: 24, marca: 'SYM', modelo: 'JOYMAX Z 300 E5+', precio: 4599, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'Media (300-400cc)', 'Carné A2', 'Scooter Sport'] },
  { id: 209, marca: 'VOGE', modelo: 'SR4 MAX', precio: 6289, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'Turismo', 'Media (300-400cc)', 'Carné A2', 'Premium', 'Scooter Sport'] },
  { id: 307, marca: 'QJMOTOR', modelo: 'SRT 700 X E5+', precio: 8499, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', '700cc+', 'Carné A2', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 243, marca: 'APRILIA', modelo: 'RX 125', precio: 4450, tags: ['Trail', 'Moto Adventure', 'Adventure', '125cc', 'Carné A1', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 350, marca: 'BMW', modelo: 'S 1000 RR', precio: 24430, tags: ['Moto Sport', 'Deportivo', 'Grande (600cc+)', '700cc+', 'Carné A', 'Carretera', 'Premium'] },
  { id: 348, marca: 'CFMOTO', modelo: '700MT', precio: 6995, tags: ['Trail', 'Moto Adventure', 'Moto Touring', 'Adventure', 'Grande (600cc+)', 'Carné A2', 'Off-road/Aventura', 'Mixta', 'Trail Turismo'] },
  { id: 195, marca: 'PEUGEOT', modelo: 'DJANGO', precio: 3285, tags: ['Scooter', 'Clásico', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 409, marca: 'BENELLI', modelo: 'BN125', precio: 2590, tags: ['Moto Naked', 'Urbana', '125cc', 'Carné A1', 'Económica', 'Carretera'] },
  { id: 46, marca: 'TRIUMPH', modelo: 'SPEED 400', precio: 5745, tags: ['Moto Naked', 'Clásico', 'Deportivo', 'Carné A2', 'Carretera', 'Premium'] },
  { id: 368, marca: 'ZONTES', modelo: '125M', precio: 3487, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Scooter Urban'] },
  { id: 250, marca: 'PEUGEOT', modelo: 'TWEET', precio: 2390, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Económica', 'Compacto', 'Scooter Urban'] },
  { id: 371, marca: 'KAWASAKI', modelo: 'VULCAN S', precio: 8260, tags: ['Moto Custom', 'Deportivo', 'Grande (600cc+)', 'Carné A2', 'Carretera'] },
  { id: 318, marca: 'YAMAHA', modelo: 'TRICITY 125', precio: 5299, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Premium', 'Scooter Urban'] },
  { id: 182, marca: 'CFMOTO', modelo: '675NK', precio: 6495, tags: ['Moto Naked', 'Deportivo', 'Grande (600cc+)', '700cc+', 'Carné A2', 'Carretera'] },
  { id: 130, marca: 'MACBOR', modelo: 'MONTANA XR5 510 E5+', precio: 6199, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Carné A2', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 358, marca: 'KAWASAKI', modelo: 'VERSYS 1100', precio: 15285, tags: ['Moto Touring', 'Trail', 'Grand Turismo', 'Adventure', 'Grande (600cc+)', '700cc+', 'Carné A', 'Carretera', 'Turismo', 'Premium', 'Trail Turismo'] },
  { id: 434, marca: 'MITT', modelo: 'TY125T-58E', precio: 3945, tags: ['Trail', 'Moto Adventure', 'Adventure', '125cc', 'Carné A1', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 815, marca: 'EFUN', modelo: 'LION', precio: 6590, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Premium', 'Scooter Urban'] },
  { id: 230, marca: 'BENELLI', modelo: 'TRK 702', precio: 6590, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', '700cc+', 'Carné A2', 'Off-road/Aventura', 'Mixta', 'Trail Deportiva'] },
  { id: 104, marca: 'HONDA', modelo: 'CL500', precio: 6100, tags: ['Moto Custom', 'Clásico', 'Carné A2', 'Urbana', 'Carretera'] },
  { id: 219, marca: 'MITT', modelo: 'TY125T-26F', precio: 3945, tags: ['Trail', 'Moto Adventure', 'Adventure', '125cc', 'Carné A1', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 167, marca: 'PIAGGIO', modelo: 'LIBERTY', precio: 2499, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Económica', 'Compacto', 'Scooter Urban'] },
  { id: 226, marca: 'KTM', modelo: 'KTM 390 ENDURO R', precio: 6399, tags: ['Trail', 'Off-road/Aventura', 'Carné A2', 'Premium'] },
  { id: 32, marca: 'KEEWAY', modelo: 'ICON 125 S', precio: 1990, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 164, marca: 'LAMBRETTA', modelo: 'V125 SPECIAL FLEX', precio: 3699, tags: ['Scooter', 'Clásico', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Premium', 'Scooter Urban'] },
  { id: 129, marca: 'KEEWAY', modelo: 'V-CRUISE', precio: 4390, tags: ['Moto Custom', 'Clásico', '125cc', 'Carné A1', 'Urbana', 'Carretera', 'Premium'] },
  { id: 288, marca: 'SILENCE', modelo: 'S01+', precio: 7500, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Premium', 'Scooter Urban'] },
  { id: 235, marca: 'KAWASAKI', modelo: 'ELIMINATOR', precio: 6825, tags: ['Moto Custom', 'Deportivo', 'Carné A2', 'Carretera'] },
  { id: 334, marca: 'MITT', modelo: '125GP', precio: 3195, tags: ['Moto Sport', 'Deportivo', '125cc', 'Carné A1', 'Carretera', 'Económica'] },
  { id: 375, marca: 'HONDA', modelo: 'CBR600R3', precio: 12700, tags: ['Moto Sport', 'Deportivo', 'Grande (600cc+)', 'Carné A2', 'Carretera', 'Premium'] },
  { id: 422, marca: 'VELCA', modelo: 'EON', precio: 7490, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Premium', 'Scooter Urban'] },
  { id: 487, marca: 'MITT', modelo: 'TY125T-26G', precio: 3195, tags: ['Trail', 'Moto Adventure', 'Adventure', '125cc', 'Carné A1', 'Off-road/Aventura', 'Económica', 'Trail Deportiva'] },
  { id: 187, marca: 'KAWASAKI', modelo: 'NINJA 500', precio: 6985, tags: ['Moto Sport', 'Deportivo', 'Carné A2', 'Carretera'] },

  // --- 201-300 (parcial: sesión sin presupuesto de búsqueda para completar el resto) ---
  { id: 201, marca: 'KTM', modelo: 'KTM 390 DUKE', precio: 6099, tags: ['Moto Naked', 'Deportivo', 'Carné A2', 'Carretera', 'Premium'] },
  { id: 397, marca: 'MITT', modelo: '125 DESERT', precio: 3495, tags: ['Trail', 'Moto Adventure', 'Adventure', '125cc', 'Carné A1', 'Off-road/Aventura', 'Económica', 'Trail Deportiva'] },
  { id: 31, marca: 'BMW', modelo: 'M 1000 XR', precio: 28950, tags: ['Moto Sport', 'Moto Touring', 'Deportivo', 'Grande (600cc+)', '700cc+', 'Carné A', 'Carretera', 'Premium'] },
  { id: 502, marca: 'BMW', modelo: 'F 900 R A2', precio: 9960, tags: ['Moto Naked', 'Deportivo', 'Grande (600cc+)', '700cc+', 'Carné A2', 'Carretera'] },
  { id: 185, marca: 'KEEWAY', modelo: 'GEMMA', precio: 2190, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Ligera (110-124cc)', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 192, marca: 'SYM', modelo: 'FUGUE 125 ABS TOP CASE', precio: 2999, tags: ['Scooter', 'Clásico', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Scooter Urban'] },
  { id: 365, marca: 'KAWASAKI', modelo: 'Z500', precio: 6189, tags: ['Moto Naked', 'Deportivo', 'Carné A2', 'Carretera'] },
  { id: 363, marca: 'KAWASAKI', modelo: 'Z500', precio: 6189, tags: ['Moto Naked', 'Deportivo', 'Carné A2', 'Carretera'] },
  { id: 398, marca: 'BAJAJ', modelo: 'PULSAR NS 400 Z', precio: 4499, tags: ['Moto Naked', 'Deportivo', 'Media (300-400cc)', 'Carné A2', 'Carretera', 'Económica'] },
  { id: 155, marca: 'PIAGGIO', modelo: 'LIBERTY 50', precio: 2499, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Económica', 'Compacto', 'Scooter Urban'] },

  // --- Resto de top 300 (completado agosto 2026) ---
  { id: 131, marca: 'LETBE', modelo: 'S125', precio: null, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] }, // nota: no se encontró un modelo LETBE "S125" en catálogos; posible código interno DGT sin correspondencia comercial clara, tags estimados por tipo de gama
  { id: 160, marca: 'MITT', modelo: 'GT-S', precio: 2695, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'City/Commuting', '125cc', 'Carné A1', 'Scooter Sport'] },
  { id: 622, marca: 'KTM', modelo: 'KTM 790 ADVENTURE', precio: 11299, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', '700cc+', 'Carné A2', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 139, marca: 'YAMAHA', modelo: 'ESS025', precio: 3599, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Bajo consumo', 'Carné A1', 'Premium', 'Scooter Urban'] }, // nota: ESS025 es el código de modelo interno del Yamaha Neo's (scooter eléctrico), no un código comercial independiente
  { id: 204, marca: 'APRILIA', modelo: 'RS 660', precio: 12310, tags: ['Moto Sport', 'Deportivo', 'Grande (600cc+)', 'Carné A2', 'Carretera', 'Premium'] },
  { id: 298, marca: 'PIAGGIO', modelo: 'VESPA PRIMAVERA', precio: 4199, tags: ['Scooter', 'Clásico', 'Urbana', 'City/Commuting', 'Carné A1', 'Premium', 'Compacto', 'Scooter Urban'] }, // nota: se asume versión 50cc (Primavera 125 ya está catalogada aparte como id 193); precio de referencia Primavera 50 E5
  { id: 382, marca: 'CYCLONE', modelo: 'RA125 PLUS', precio: 3090, tags: ['Moto Custom', 'Clásico', '125cc', 'Carné A1', 'Urbana', 'Carretera', 'Económica'] },
  { id: 458, marca: 'MACBOR', modelo: 'ROCKSTER 125 EVO E5+', precio: 2499, tags: ['Trail', 'Moto Adventure', 'Adventure', '125cc', 'Carné A1', 'Off-road/Aventura', 'Económica', 'Trail Deportiva'] },
  { id: 173, marca: 'LETBE', modelo: 'ISLAND', precio: 2890, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 263, marca: 'CYCLONE', modelo: 'RT1', precio: 2795, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'City/Commuting', '125cc', 'Carné A1', 'Scooter Sport'] },
  { id: 299, marca: 'KEEWAY', modelo: 'FACT EVO 50 X', precio: null, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Económica', 'Compacto', 'Scooter Urban'] }, // nota: no se confirmó precio fiable específico de la variante "X"
  { id: 189, marca: 'MORBIDELLI', modelo: 'F125', precio: 2790, tags: ['Moto Naked', 'Deportivo', '125cc', 'Carné A1', 'Carretera', 'Económica'] },
  { id: 107, marca: 'QJMOTOR', modelo: 'LTS 50 S', precio: 2199, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Económica', 'Compacto', 'Scooter Urban'] },
  { id: 142, marca: 'SUZUKI', modelo: 'GSX-S125', precio: 3699, tags: ['Moto Naked', 'Deportivo', '125cc', 'Carné A1', 'Carretera'] },
  { id: 158, marca: 'KAWASAKI', modelo: 'Z125', precio: 5125, tags: ['Moto Naked', 'Deportivo', '125cc', 'Carné A1', 'Carretera', 'Premium'] },
  { id: 212, marca: 'CFMOTO', modelo: '125 NK', precio: 3395, tags: ['Moto Naked', 'Deportivo', '125cc', 'Carné A1', 'Carretera', 'Económica'] },
  { id: 245, marca: 'DUCATI', modelo: 'PANIGALE V2', precio: 17490, tags: ['Moto Sport', 'Deportivo', 'Grande (600cc+)', '700cc+', 'Carné A', 'Carretera', 'Premium'] },
  { id: 282, marca: 'HONDA', modelo: 'CB 500 F', precio: 6175, tags: ['Moto Naked', 'Deportivo', 'Carné A2', 'Carretera'] },
  { id: 323, marca: 'KAWASAKI', modelo: 'NINJA 125', precio: 5575, tags: ['Moto Sport', 'Deportivo', '125cc', 'Carné A1', 'Carretera', 'Premium'] },
  { id: 54, marca: 'SYM', modelo: 'FIDDLE 50 E5+', precio: 2399, tags: ['Scooter', 'Clásico', 'Urbana', 'City/Commuting', 'Económica', 'Compacto', 'Scooter Urban'] },
  { id: 86, marca: 'HUSQVARNA', modelo: 'HUSQVARNA TE 300', precio: 11395, tags: ['Trail', 'Off-road/Aventura', 'Carné A', '300cc', 'Premium'] },
  { id: 281, marca: 'APRILIA', modelo: 'SR GT 400', precio: 6750, tags: ['Scooter', 'Crossover', 'Adventure', 'Media (300-400cc)', 'Carné A2', 'Mixta', 'Scooter Adventure'] },
  { id: 266, marca: 'SUZUKI', modelo: 'DR-Z400', precio: 8999, tags: ['Trail', 'Off-road/Aventura', 'Carné A2'] }, // nota: nameplate ya no comercializado; sucesor actual DR-Z4S, precio usado como referencia
  { id: 106, marca: 'MACBOR', modelo: 'ROCKSTER FLAT 125 EVO', precio: 2599, tags: ['Trail', 'Moto Adventure', 'Adventure', '125cc', 'Carné A1', 'Off-road/Aventura', 'Económica', 'Trail Deportiva'] },
  { id: 2, marca: 'MITT', modelo: '125GTS', precio: 2695, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'City/Commuting', 'Carretera', '125cc', 'Carné A1', 'Económica', 'Scooter Sport'] },
  { id: 319, marca: 'MACBOR', modelo: 'EIGHT MILE 125 LC', precio: 3299, tags: ['Moto Naked', 'Clásico', 'Urbana', '125cc', 'Carné A1', 'Económica', 'Carretera'] },
  { id: 474, marca: 'KAWASAKI', modelo: 'ELIMINATOR', precio: 6699, tags: ['Moto Custom', 'Clásico', 'Carné A2', 'Urbana', 'Carretera'] },
  { id: 251, marca: 'APRILIA', modelo: 'SX 125', precio: 4550, tags: ['Trail', 'Off-road/Aventura', 'Adventure', '125cc', 'Carné A1', 'Deportivo', 'Mixta'] },
  { id: 224, marca: 'CYCLONE', modelo: 'LS-Z', precio: null, tags: ['Trail', 'Off-road/Aventura', '125cc', 'Carné A1', 'Económica'] }, // nota: modelo "LS-Z" no localizado en el catálogo Cyclone España (gama conocida: RX1/RX1 Pro/RX2/RX4/Carrera/Battlo); posible modelo no comercializado en España o nombre DGT distinto
  { id: 374, marca: 'MOTO MORINI', modelo: 'X-CAPE', precio: 7190, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', 'Carné A2', 'Off-road/Aventura', 'Mixta', 'Trail Deportiva'] },
  { id: 246, marca: 'KTM', modelo: 'KTM 125 ENDURO', precio: 5499, tags: ['Trail', 'Off-road/Aventura', '125cc', 'Carné A1', 'Adventure', 'Premium'] },
  { id: 283, marca: 'KTM', modelo: 'KTM 125 SMC R', precio: 5399, tags: ['Moto Sport', 'Deportivo', '125cc', 'Carné A1', 'Carretera', 'Premium'] },
  { id: 256, marca: 'MORBIDELLI', modelo: 'T502X', precio: 5390, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Carné A2', 'Off-road/Aventura', 'Trail Deportiva', 'Económica'] },
  { id: 305, marca: 'TRIUMPH', modelo: 'SCRAMBLER 400 X', precio: 6445, tags: ['Moto Naked', 'Clásico', 'Crossover', 'Carné A2', 'Mixta', 'Carretera', 'Off-road/Aventura', 'Premium'] },
  { id: 345, marca: 'SHERCO', modelo: '300 SE-R', precio: null, tags: ['Trail', 'Off-road/Aventura', 'Carné A2', 'Premium'] }, // nota: modelo de 2021 aparentemente descontinuado, sustituido por gama "SE Racing"; sin PVP oficial vigente fiable
  { id: 372, marca: 'HONDA', modelo: 'CMX1100', precio: 11450, tags: ['Moto Custom', 'Clásico', 'Grande (600cc+)', '700cc+', 'Carné A', 'Carretera', 'Premium'] },
  { id: 983, marca: 'SILENCE', modelo: 'SEAT MÓ ESCOOTER 125', precio: 6250, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Bajo consumo', 'Carné A1', 'Premium', 'Scooter Urban'] },
  { id: 367, marca: 'NEXT', modelo: 'NX CROSS 125I', precio: 2999, tags: ['Trail', 'Moto Adventure', 'Adventure', '125cc', 'Carné A1', 'Off-road/Aventura', 'Económica'] },
  { id: 418, marca: 'KAWASAKI', modelo: 'Z650RS', precio: 8399, tags: ['Moto Naked', 'Clásico', 'Grande (600cc+)', 'Carné A2', 'Carretera'] },
  { id: 186, marca: 'TRIUMPH', modelo: 'TRIDENT 660', precio: 8295, tags: ['Moto Naked', 'Deportivo', 'Grande (600cc+)', 'Carné A2', 'Carretera', 'Premium'] },
  { id: 337, marca: 'CYCLONE', modelo: 'RX1 PRO', precio: 3385, tags: ['Trail', 'Moto Adventure', 'Adventure', '125cc', 'Carné A1', 'Off-road/Aventura', 'Económica'] },
  { id: 524, marca: 'ROYAL ENFIELD', modelo: 'INTERCEPTOR BEAR 650', precio: 7287, tags: ['Moto Custom', 'Clásico', 'Grande (600cc+)', 'Carné A2', 'Carretera', 'Off-road/Aventura', 'Mixta'] }, // nota: interpretado como Royal Enfield Bear 650 (scrambler sobre base Interceptor 650); nombre DGT no corresponde a un único modelo comercial
  { id: 380, marca: 'HONDA', modelo: 'ST125A', precio: 4450, tags: ['Moto Custom', 'Clásico', '125cc', 'Carné A1', 'Urbana', 'Carretera', 'Compacto', 'Premium'] },
  { id: 438, marca: 'BMW', modelo: 'R 12 G/S', precio: 18090, tags: ['Trail', 'Moto Adventure', 'Clásico', 'Adventure', 'Grande (600cc+)', 'Carné A', 'Off-road/Aventura', 'Premium', 'Trail Deportiva'] },
  { id: 551, marca: 'YAMAHA', modelo: 'XSR-900', precio: 12299, tags: ['Moto Naked', 'Clásico', 'Grande (600cc+)', '700cc+', 'Carné A', 'Carretera', 'Premium'] },
  { id: 273, marca: 'KTM', modelo: 'KTM 790 DUKE', precio: 8799, tags: ['Moto Naked', 'Deportivo', 'Grande (600cc+)', '700cc+', 'Carné A2', 'Carretera', 'Premium'] },
  { id: 443, marca: 'DUCATI', modelo: 'STREETFIGHTER', precio: 15090, tags: ['Moto Naked', 'Deportivo', 'Grande (600cc+)', 'Carné A', 'Carretera', 'Premium'] },
  { id: 642, marca: 'ITALJET', modelo: 'DRAGSTER 700 TWIN', precio: 12900, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'Grande (600cc+)', '700cc+', 'Carné A2', 'Carretera', 'Premium', 'Scooter Sport'] },
  { id: 626, marca: 'ZONTES', modelo: '350R', precio: 4387, tags: ['Moto Naked', 'Deportivo', 'Media (300-400cc)', 'Carné A2', 'Carretera', 'Económica'] },
  { id: 239, marca: 'BENELLI', modelo: 'BKX 125', precio: 3790, tags: ['Trail', 'Moto Adventure', 'Adventure', '125cc', 'Carné A1', 'Off-road/Aventura', 'Económica', 'Trail Deportiva'] },
  { id: 565, marca: 'QJMOTOR', modelo: 'SRT 700 E5+', precio: 7999, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', '700cc+', 'Carné A2', 'Off-road/Aventura', 'Mixta', 'Trail Turismo'] },
  { id: 236, marca: 'BAJAJ', modelo: 'DOMINAR D 400', precio: 4499, tags: ['Moto Naked', 'Deportivo', 'Carné A2', 'Carretera', 'Económica', 'Touring'] }, // precio orientativo, hay promos puntuales según fuente
  { id: 90, marca: 'KEEWAY', modelo: 'VIESTE 125XDV', precio: 2790, tags: ['Scooter', 'Crossover', 'Adventure', '125cc', 'Carné A1', 'Económica', 'City/Commuting', 'Scooter Adventure'] },
  { id: 326, marca: 'MOTO MORINI', modelo: 'SEIEMMEZZO', precio: 4390, tags: ['Moto Naked', 'Clásico', 'Grande (600cc+)', 'Carné A2', 'Carretera', 'Premium'] }, // asumida versión STR (naked, entrada)
  { id: 393, marca: 'YAMAHA', modelo: 'MT-03', precio: 6399, tags: ['Moto Naked', 'Deportivo', 'Media (300-400cc)', 'Carné A2', 'Carretera'] },
  { id: 11, marca: 'BENDA', modelo: 'LFC700', precio: 11990, tags: ['Moto Custom', 'Clásico', 'Grande (600cc+)', '700cc+', 'Carné A2', 'Carretera', 'Premium'] },
  { id: 274, marca: 'QJMOTOR', modelo: 'LTR 125 E5+', precio: 2999, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 491, marca: 'MORBIDELLI', modelo: 'SC 125', precio: 2690, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 834, marca: 'TRIUMPH', modelo: 'TIGER 900 GT PRO', precio: 15895, tags: ['Trail', 'Moto Adventure', 'Moto Touring', 'Adventure', 'Grande (600cc+)', '700cc+', 'Carné A2', 'Off-road/Aventura', 'Mixta', 'Premium', 'Trail Turismo'] },
  { id: 177, marca: 'KYMCO', modelo: 'XCITING VS 400', precio: 6590, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'Media (300-400cc)', 'Carné A2', 'Premium', 'Scooter Sport'] },
  { id: 309, marca: 'TRIUMPH', modelo: 'SPEED TWIN 900', precio: 9995, tags: ['Moto Naked', 'Clásico', 'Grande (600cc+)', '700cc+', 'Carné A2', 'Carretera', 'Premium'] },
  { id: 343, marca: 'KTM', modelo: 'KTM 890 ADVENTURE R', precio: 14399, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', '700cc+', 'Carné A', 'Off-road/Aventura', 'Premium', 'Trail Deportiva'] },
  { id: 295, marca: 'HONDA', modelo: 'CB500FAC', precio: 6175, tags: ['Moto Naked', 'Deportivo', 'Grande (600cc+)', 'Carné A2', 'Carretera'] },
  { id: 644, marca: 'KAWASAKI', modelo: 'NINJA ZX-10R', precio: 20150, tags: ['Moto Sport', 'Deportivo', 'Grande (600cc+)', 'Carné A', 'Carretera', 'Premium'] },
  { id: 132, marca: 'SILENCE', modelo: 'S02', precio: 2990, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Carné A1', 'Bajo consumo', 'Económica', 'Scooter Urban'] },
  { id: 154, marca: 'MH MOTORCYCLES', modelo: 'RAPTOR', precio: 1995, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Compacto', 'Económica', 'Scooter Urban'] }, // asumido MH Raptor 50
  { id: 170, marca: 'SUZUKI', modelo: 'BURGMAN 400', precio: 8875, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'Media (300-400cc)', 'Carné A2', 'Premium', 'Turismo', 'Scooter Sport'] },
  { id: 333, marca: 'QJMOTOR', modelo: 'SRV 12 E5+', precio: 3899, tags: ['Moto Custom', 'Clásico', '125cc', 'Carné A1', 'Carretera', 'Económica', 'Urbana'] },
  { id: 472, marca: 'BMW', modelo: 'R 12 NINET', precio: 18250, tags: ['Moto Custom', 'Clásico', 'Grande (600cc+)', 'Carné A', 'Carretera', 'Premium'] },
  { id: 248, marca: 'SILENCE', modelo: 'S04', precio: 8839, tags: ['City/Commuting', 'Bajo consumo', 'Económica', 'Compacto'] }, // nota: el S04 es un cuadriciclo ligero eléctrico (L6e/L7e), no una moto propiamente dicha
  { id: 505, marca: 'LETBE', modelo: 'VELOCITY', precio: 2490, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 208, marca: 'KTM', modelo: 'KTM 390 SMC R', precio: 6249, tags: ['Moto Naked', 'Deportivo', 'Media (300-400cc)', 'Carné A2', 'Carretera'] },
  { id: 311, marca: 'MORBIDELLI', modelo: 'SC125LX', precio: 2490, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 15, marca: 'BSA', modelo: 'BANTAM', precio: 3592, tags: ['Moto Clásica', 'Clásico', 'Media (300-400cc)', 'Carné A2', 'Carretera', 'Económica', 'Urbana'] }, // BSA Bantam 350, precio promocional España
  { id: 420, marca: 'KAWASAKI', modelo: 'Z900RS', precio: 14300, tags: ['Moto Clásica', 'Clásico', 'Grande (600cc+)', '700cc+', 'Carné A', 'Carretera', 'Premium'] },
  { id: 481, marca: 'APRILIA', modelo: 'RS 457', precio: 6999, tags: ['Moto Sport', 'Deportivo', 'Carné A2', 'Carretera'] },
  { id: 407, marca: 'SHERCO', modelo: '125 SE-R', precio: 4899, tags: ['Trail', 'Adventure', 'Off-road/Aventura', '125cc', 'Carné A1', 'Premium'] }, // precio de la variante 4T SE-RS Factory actualmente comercializada
  { id: 774, marca: 'SUPER SOCO', modelo: 'CPX', precio: 4289, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Bajo consumo', 'Carné A1', 'Premium', 'Scooter Urban'] },
  { id: 486, marca: 'EFUN', modelo: 'PUSA90', precio: null, tags: ['Scooter', 'Urbana', 'City/Commuting', 'Bajo consumo', 'Económica'] }, // solo se encuentran anuncios de particulares/tiendas no oficiales, sin PVP oficial fiable
  { id: 109, marca: 'KEEWAY', modelo: 'VERSILIA 125', precio: 2390, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 244, marca: 'CYCLONE', modelo: 'RX600', precio: 5290, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Grande (600cc+)', 'Carné A2', 'Off-road/Aventura', 'Económica', 'Trail Deportiva'] },
  { id: 496, marca: 'QJMOTOR', modelo: 'SRK 125 R E5+', precio: 3799, tags: ['Moto Naked', 'Deportivo', '125cc', 'Carné A1', 'Carretera', 'Económica'] }, // precio con seguro incluido; base sin seguro 3.299€
  { id: 744, marca: 'BMW', modelo: 'R 1300 R', precio: 17670, tags: ['Moto Naked', 'Deportivo', 'Grande (600cc+)', '700cc+', 'Carné A', 'Carretera', 'Premium'] },
  { id: 175, marca: 'BENDA', modelo: 'CHINCHILLA', precio: 6250, tags: ['Moto Custom', 'Clásico', 'Carné A2', 'Carretera', 'Urbana'] }, // asumida versión Chinchilla 500 (475,6cc)
  { id: 519, marca: 'TRIUMPH', modelo: 'STREET TRIPLE RS', precio: 13895, tags: ['Moto Naked', 'Deportivo', 'Grande (600cc+)', '700cc+', 'Carné A', 'Carretera', 'Premium'] },
  { id: 456, marca: 'HONDA', modelo: 'MSX125A', precio: 4200, tags: ['Moto Naked', 'Urbana', '125cc', 'Carné A1', 'City/Commuting', 'Compacto', 'Económica'] }, // Honda MSX125 Grom
  { id: 424, marca: 'KOVE', modelo: '450 RALLY 2026', precio: 9499, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Carné A2', 'Off-road/Aventura', 'Trail Deportiva'] }, // versión Regular Edition 2026
  { id: 483, marca: 'KTM', modelo: 'KTM 390 ADVENTURE X', precio: 5999, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Media (300-400cc)', 'Carné A2', 'Off-road/Aventura', 'Trail Deportiva'] },
  { id: 241, marca: 'MH MOTORCYCLES', modelo: 'VRS', precio: 3295, tags: ['Scooter', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Scooter Urban'] },
  { id: 255, marca: 'MORBIDELLI', modelo: 'SC125 RE', precio: 2690, tags: ['Scooter', 'Clásico', 'Urbana', 'City/Commuting', '125cc', 'Carné A1', 'Económica', 'Scooter Urban'] },
  { id: 302, marca: 'KEEWAY', modelo: 'RKF 125 ABS', precio: 3190, tags: ['Moto Naked', 'Deportivo', '125cc', 'Carné A1', 'Carretera', 'Económica'] },
  { id: 344, marca: 'PIAGGIO', modelo: 'BEVERLY 400 HPE', precio: 6799, tags: ['Scooter', 'Deportivo', 'Grand Turismo', 'Media (300-400cc)', 'Carné A2', 'Turismo', 'Scooter Sport'] },
  { id: 384, marca: 'CFMOTO', modelo: 'DUAL250', precio: 2995, tags: ['Trail', 'Moto Adventure', 'Adventure', 'Carné A2', 'Off-road/Aventura', 'Económica', 'Trail Deportiva'] },
];

module.exports = { CURATED };
